apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vlkyd8uwh-go 
  janus-idp.io/tekton: vlkyd8uwh-go
  backstage.io/kubernetes-id: vlkyd8uwh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vlkyd8uwh-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  